binutils: binutils-build

$(BINUTILS-SRC-PATH): | $(BINUTILS-TAR-PATH) $(SRCDIR)
	$(TAR) -xf $(BINUTILS-TAR-PATH) -C $(SRCDIR)
	$(PATCH) -p1 -l -s -d $(BINUTILS-SRC-PATH) -i $(BINUTILS-PATCH-PATH)

$(BINUTILS-TAR-PATH): | $(SRCDIR)
	$(WGET) $(BINUTILS-URL) -O $(BINUTILS-TAR-PATH)

$(BINUTILS-BUILD-PATH): | $(BUILDDIR)
	$(MKDIR) $(BUILDDIR)/$(BINUTILS)

$(BINUTILS-CONFIGURE-FLAG): | $(BINUTILS-SRC-PATH) $(BINUTILS-BUILD-PATH)
	$(CD) $(BINUTILS-BUILD-PATH) && $(BINUTILS-SRC-PATH)/configure \
		--target=$(TARGET) --prefix=$(PREFIX) \
		--disable-werror --disable-nls --enable-plugins

$(BINUTILS-BUILD-FLAG): $(BINUTILS-CONFIGURE-FLAG) 
	$(MAKE) -C $(BINUTILS-BUILD-PATH) && \
	$(TOUCH) $(BINUTILS-BUILD-FLAG)

$(BINUTILS-INSTALL-FLAG): $(BINUTILS-BUILD-FLAG)
	$(MAKE) install -C $(BINUTILS-BUILD-PATH)
	$(TOUCH) $(BINUTILS-INSTALL-FLAG) 

binutils-fetch: $(BINUTILS-SRC-PATH)

binutils-configure: $(BINUTILS-CONFIGURE-FLAG)

binutils-build: $(BINUTILS-BUILD-FLAG)

binutils-install: $(BINUTILS-INSTALL-FLAG)
